/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3-dev at Sat Mar 21 22:10:23 2015. */

#ifndef PB_SECOND_PB_H_INCLUDED
#define PB_SECOND_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _SecondMessage {
    bool lucky_punch;
} SecondMessage;

typedef struct _ThirdMessage {
    bool hope;
} ThirdMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SecondMessage_init_default               {0}
#define ThirdMessage_init_default                {0}
#define SecondMessage_init_zero                  {0}
#define ThirdMessage_init_zero                   {0}

/* Field tags (for use in manual encoding/decoding) */
#define SecondMessage_lucky_punch_tag            1
#define ThirdMessage_hope_tag                    1

/* Struct field encoding specification for nanopb */
extern const pb_field_t SecondMessage_fields[2];
extern const pb_field_t ThirdMessage_fields[2];

/* Maximum encoded size of messages (where known) */
#define SecondMessage_size                       2
#define ThirdMessage_size                        2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
