/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.3-dev at Sat Mar 21 22:04:18 2015. */

#include "second.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SecondMessage_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, SecondMessage, lucky_punch, lucky_punch, 0),
    PB_LAST_FIELD
};


