/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.3-dev at Sun Mar 22 01:51:53 2015. */

#include "simple.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SimpleMessage_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SimpleMessage, lucky_number, lucky_number, 0),
    PB_LAST_FIELD
};

const pb_field_t DuplicatedMessage_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DuplicatedMessage, serial, serial, 0),
    PB_LAST_FIELD
};


